export const defaultGoals = [
   {
      id: "ano1-lumos",
      year: 1,
      type: "spell",
      title: "Lumos",
      description: "Produz luz na ponta da varinha.",
      target: 10,
      source_key: "c0910cff-7391-431f-b7bd-60891313e16b",
   },
   {
      id: "ano1-nox",
      year: 1,
      type: "spell",
      title: "Nox",
      description: "Apaga a luz produzida por Lumos.",
      target: 10,
      source_key: "3decffc8-99a7-47b1-8b10-aa593f6a37e0",
   },
   {
      id: "ano1-wingardium-leviosa",
      year: 1,
      type: "spell",
      title: "Wingardium Leviosa",
      description: "Levita objetos.",
      target: 10,
      source_key: "ca6ffa35-81f9-4987-ad65-37714c9dcb28",
   },
   {
      id: "ano1-alohomora",
      year: 1,
      type: "spell",
      title: "Alohomora",
      description: "Abre fechaduras.",
      target: 10,
      source_key: "7de16be0-9048-4024-93d4-da5a2e365b31",
   },
   {
      id: "ano1-reparo",
      year: 1,
      type: "spell",
      title: "Reparo (objetos pequenos)",
      description: "Conserta objetos.",
      target: 5,
      source_key: "17d54e10-1632-4b29-b8fe-16a3a2d45cb0",
   },
   {
      id: "ano1-petrificus-totalus",
      year: 1,
      type: "spell",
      title: "Petrificus Totalus",
      description: "Paralisa o corpo da vítima.",
      target: 5,
      source_key: "e74a7af9-5ff9-4005-aefa-f37201f4bb15",
   },
   {
      id: "ano1-locomotor-mortis",
      year: 1,
      type: "spell",
      title: "Locomotor Mortis",
      description: "Prende as pernas da vítima.",
      target: 5,
      source_key: "61a068b0-ef05-45df-bbc8-4e8f2444d72b",
   },
   {
      id: "ano1-incendio",
      year: 1,
      type: "spell",
      title: "Incendio",
      description: "Produz fogo.",
      target: 5,
      source_key: "6b3a77ab-4a1c-40ac-a184-39221ee4c33b",
   },
   {
      id: "ano1-cure-for-boils",
      year: 1,
      type: "potion",
      title: "Poção para Cura de Furúnculos",
      description: "Aprende a achar ingredientes e produzir.",
      target: 10,
      source_key: "f8374cda-4769-49ba-90e0-abf856888ee7",
   },
   {
      id: "ano1-pocao-revigorante",
      year: 1,
      type: "potion",
      title: "Poção Revigorante",
      description: "Aprende a achar ingredientes e produzir.",
      target: 5,
      source_key: "pocao-revigorante",
   },
   {
      id: "ano1-coragem",
      year: 1,
      type: "attribute",
      title: "Coragem",
      description: "Requerido por ser da Grifinória.",
      target: 10,
      source_key: "Coragem",
   },
   {
      id: "ano1-magia",
      year: 1,
      type: "attribute",
      title: "Magia",
      description: "Requerido para passar nas provas finais.",
      target: 7,
      source_key: "Magia",
   },
   {
      id: "ano1-controle",
      year: 1,
      type: "attribute",
      title: "Controle",
      description: "Requerido para passar nas provas finais.",
      target: 7,
      source_key: "Controle",
   },
];

export const goalTypes = [
   { value: "spell", label: "Feitiço", collectionKey: "habilidades" },
   { value: "potion", label: "Poção", collectionKey: "pocoes" },
   { value: "attribute", label: "Atributo", collectionKey: "atributos" },
   { value: "mystery", label: "Mistério", collectionKey: "mysteries" },
   { value: "custom", label: "Manual", collectionKey: "custom" },
];
